#PBS -q regular
# Setting number of cores multiples of 24 (since 24 cores per NUMA node) 
#PBS -l mppwidth=1008
#PBS -l walltime=00:40:00
#PBS -N 2dOTmhd_courant_test 
#PBS -e test.$PBS_JOBID.err
#PBS -o test.$PBS_JOBID.out
#PBS -A m2218
module swap PrgEnv-gnu PrgEnv-intel
cd /project/projectdirs/astro250/doris/mhd_test/courant_test/
pwd
aprun -n 1000 /project/projectdirs/astro250/doris/ramses/trunk/ramses/bin/ramses2d_mhd_otpatch orszag-tang.nml
